### PR TITLE
Add s-chop-left and s-chop-right

### PR DESCRIPTION
**Pull request by cy20lin**
These two functions increase readability, when wanting to chop the string by length from its left or right.
e.g. 
previously

    (s-right (- (length a-string) 3) a-string)
now becomes 

    (s-chop-left 3 a-string)

### CODE REVIEW

**Comment by daantjie** [comment]
I was actually about to implement something like this! Good thing I saw this in time...

However, I find it a little confusing that the functions chop *up to* the `len`th item; why not have it just chop off `len` items? That's what `s-left` and `s-right` do (except they keep `len` items).

**Comment by cy20lin** [comment]
Let me explain these functions in detail, take `s-chop-left` for example:

Consider following expressions.
```cl
(setq strlen (length str))
(s-chop-left len str)
```
* if `len` is negative, it throws an error.
* if `len` is equal to zero, it does nothing but return a string same as `str`, e.g.

    ```cl
    (s-chop-left 0 "123456789") ;; => "123456789"
    ```
* if `len` is greater then zero and less than `strlen`, it returns `str` with `len` chars from its left is removed, e.g.

    ```cl
    (s-chop-left 4 "123456789") ;; => "56789" ; 4 chars is removed (from left)
    (s-chop-left 7 "123456789") ;; => "89"    ; 7 chars is removed (from left)
    ```
* if `len` is equal to or greater than `strlen`, it returns an empty string, e.g

    ```cl
    (s-chop-left 9  "123456789") ;; => ""      ; 9 chars is removed (from left)
    (s-chop-left 99 "123456789") ;; => ""      ; 9 chars is removed (from left)
    ```

`s-chop-right` works the same as `s-chop-left` except that it chops form the right side.

----
@daantjie, I think these functions work just as you supposed they to be. 
* They **chop off** exactly `len` chars, if `len` is in the range `[0, strlen]`.
* They **chop up to** `strlen` chars, if `len` exceeds `strlen`.

Don't they?

**Comment by daantjie** [comment]
@cy20lin: right you are! What confused me was the docstrings:

> "Remove **up to** the LEN first/last chars of S."

I would interpret that as *up to (but not including)* – maybe change the docstring to something like the following?

> "Remove the first/last LEN chars."

**Comment by jasonm23** [comment]
Looks good to me, sorry about the delay on this PR. I'm joining s.el as an assistant maintainer.  I'll help to get this merged.

**Pull request merged**
