### PR TITLE
Add crazy-s-get-style-case

### LINKED ISSUE #164: 🐣 [REQUEST] - <title>
### Implementation PR

_No response_

### Reference Issues

_No response_

### Summary

It would be nice to have some way to check if a given string has given style, say like `s-snake-case-p` `s-upper-camel-case-p` etc. My use case is to cycle the string between styles based on current style of the string.

### Basic Example

```elisp
(s-snake-case-p "hello_world")` ;; t
(s-snake-case-p "hello-world-again")` ;; f
```

### Drawbacks

When there is no separator, it may not be properly able to guess the style, eg: if the string is `"hello"`.
Also, there should be a priority order, eg: for the string `"hello_WorldAgain" if snake case is prioritized, it should be reported as snake case. Setting priority shall also help solve the previously said issue, the priority order could be something like: snake case, lisp-case, camel-case, upper-camel-case

### PR DESCRIPTION
**Pull request by pksadiq**
Fixes #164

I'm not sure if the defun name is good enough

### CODE REVIEW

**Comment by jasonm23** [comment]
Initial thoughts

Only provide return styles which match s funcs e.g. - s-dashed-words = s-dashed-words-p.  Etc. Do not add aliases such as lisp-case, kebab-case etc.  Consider the existing names as canon, adhere to them.

Do not return strings.  Only provide predicates which are nil/non-nil so the compiler can check/assist.

Avoid the ever expanding cond, favor pcase when a combined pattern match is needed.

**Comment by pksadiq** [comment]
Changed to use `pcase`, and used `rx` for regex so that it's easier to read. I don't have deep knowledge in elisp, so I'm not sure regarding the predicate stuff.  Let me know if I want to implement those defuns to return `t`/`nil` (which is what I guess predicate functions are about), or are they used only for testing?

**Comment by jasonm23** [comment]
For the predicates, I meant that's how to implement the solution.

No single conditional engine to detect style, instead, individual predicate functions named as per the existing `s` function which converts to the same style.

**Comment by pksadiq** [comment]
I copied the relevant code from s.el and adapted to my need.  Also, i don't have time to look into this further.  If anyone want to use (and/or improve) this, feel free to do so.

Closing.

**Pull request closed without merging**
